services:
  db:
    image: postgres:17-alpine
    container_name: easypet-ecommerce
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: easypet_ecommerce
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: easypet-redis-ecommerce
    ports:
      - "6379:6379"

volumes:
  pgdata: